export const GET_GENRES = 'GET_GENRES';

export const GET_POPULAR = 'GET_POPULAR';
export const GET_POPULAR_START = 'GET_POPULAR_START';
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS';
export const GET_POPULAR_FAIL = 'GET_POPULAR_FAIL';

export const GET_TRENDING = 'GET_TRENDING';
export const GET_TRENDING_START = 'GET_TRENDING_START';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAIL = 'GET_TRENDING_FAIL';

export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_SEARCH_RESULTS_START = 'GET_SEARCH_RESULTS_START';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const GET_SEARCH_RESULTS_FAIL = 'GET_SEARCH_RESULTS_FULL';

